from collections.abc import Iterable

class ItemCount:
    key: str
    count: int
    error: int
    def __iter__(self) -> Iterable[str | int]: ...

class BloomFilter:
    def __init__(self, capacity: int, error_rate: float) -> None: ...
    def add(self, item: str) -> None: ...
    def update(self, items: Iterable[str]) -> None: ...
    def might_contain(self, item: str) -> bool: ...
    def __contains__(self, item: str) -> bool: ...
    def merge(self, other: BloomFilter) -> None: ...
    @property
    def capacity(self) -> int: ...
    @property
    def error_rate(self) -> float: ...
    @property
    def bit_count(self) -> int: ...
    @property
    def hash_count(self) -> int: ...
    @property
    def fill_ratio(self) -> float: ...
    @property
    def size_bytes(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> BloomFilter: ...
    def __eq__(self, other: object) -> bool: ...

class HyperLogLog:
    def __init__(self, precision: int = 14) -> None: ...
    def add(self, item: str) -> None: ...
    def update(self, items: Iterable[str]) -> None: ...
    def merge(self, other: HyperLogLog) -> None: ...
    def estimate(self) -> float: ...
    @property
    def precision(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> HyperLogLog: ...
    def __eq__(self, other: object) -> bool: ...

class CountMinSketch:
    def __init__(self, width: int, depth: int) -> None: ...
    @staticmethod
    def from_error(epsilon: float, delta: float) -> CountMinSketch: ...
    def add(self, item: str, count: int = 1) -> None: ...
    def update(self, items: Iterable[str]) -> None: ...
    def estimate(self, item: str) -> int: ...
    def merge(self, other: CountMinSketch) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> CountMinSketch: ...
    def __eq__(self, other: object) -> bool: ...

class Reservoir:
    def __init__(self, capacity: int, seed: int = 0x5EED1234C0FFEE) -> None: ...
    def add(self, value: float) -> None: ...
    def update(self, values: Iterable[float]) -> None: ...
    def quantile(self, q: float) -> float: ...
    def sample(self) -> list[float]: ...
    @property
    def capacity(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def seen(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> Reservoir: ...
    def __eq__(self, other: object) -> bool: ...

class SpaceSaving:
    def __init__(self, k: int) -> None: ...
    def add(self, item: str, count: int = 1) -> None: ...
    def update(self, items: Iterable[str]) -> None: ...
    def monitored(self, item: str) -> bool: ...
    def upper_bound(self, item: str) -> int: ...
    def lower_bound(self, item: str) -> int: ...
    def top(self, n: int | None = None) -> list[ItemCount]: ...
    @property
    def k(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> SpaceSaving: ...
    def __eq__(self, other: object) -> bool: ...
